config/routes.rb
UserAuth::Application.routes.draw do

 

  resources :jobs
  match ':controller(/:action(/:id))(.:format)'
  root :to => 'sessions#login'
  match "signup", :to => "users#new"
  match "login", :to => "sessions#login"
  match "logout", :to => "sessions#logout"
  match "home", :to => "sessions#home"
  match "profile", :to => "sessions#profile"
  match "setting", :to => "sessions#setting"
  match "admin", :to => "activities#index"
  match "jobs_user", :to => "jobs#index_user"
  match "apply/id", :to => "sessions#apply"
  match 'users/id', :to => 'sessions#profile' 
  match "all_users", :to => "users#index"

end

app/models/job.rb
class Job < ActiveRecord::Base
	include PublicActivity::Model
	tracked owner: ->(controller, model) { controller && controller.current_user}
	serialize :applicants, Array
	serialize :apply_date, Array
	attr_accessible :project_name, :country, :start_date, :end_date, :brief_description, :job_description, :work_information, :skills, :language, :other_details, :applicants, :apply_date, :status
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user
  before_filter :auth_admin, :only => [:index, :new, :edit, :create, :update]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end
  
  # GET /jobs_user
  def index_user
	@jobs = Job.all

    respond_to do |format|
      format.html # index_user.html.erb
      format.json { render json: @jobs }
    end
  end
  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    @job.status = 0
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.status = 1
    @job.save
    redirect_to jobs
    # @job.destroy

    # respond_to do |format|
    #   format.html { redirect_to jobs_url }
    #   format.json { head :no_content }
    # end
  end
  def del
    @job = Job.find(params[:id])
    @job.status = 1
    @job.save
    redirect_to Job
    # @job.destroy

    # respond_to do |format|
    #   format.html { redirect_to jobs_url }
    #   format.json { head :no_content }
    # end
  end
  def restore
    @job = Job.find(params[:id])
    @job.status = 0
    @job.save
    redirect_to Job
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %><br />
    <%= f.text_field :project_name,{:class => "form-control",:placeholder => "Project Name",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country,{:class => "form-control",:placeholder => "Country",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.text_field :start_date,{:class => "form-control",:placeholder => "Start Date",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.text_field :end_date,{:class => "form-control",:placeholder => "End Date",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :brief_description %><br />
    <%= f.text_area :brief_description,{:class => "form-control",:placeholder => "Breif Description",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :project_description %><br />
    <%= f.text_area :job_description,{:class => "form-control",:placeholder => "Project Description",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :work_information %><br />
    <%= f.text_area :work_information,{:class => "form-control",:placeholder => "Work Information",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :skills %><br />
    <%= f.text_area :skills,{:class => "form-control",:placeholder => "Skills",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language,{:class => "form-control",:placeholder => "Language",:required => true} %>
  </div>
  <div class="field">
    <%= f.label :other_details %><br />
    <%= f.text_area :other_details,{:class => "form-control",:placeholder => "Other Details",:required => true} %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-success" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Show', @job ,:class => "btn btn-info"%> |
<%= link_to 'Back', jobs_path ,:class => "btn btn-danger"%>

app/views/jobs/index.html.erb
<h1 style="font-weight: 200; margin-left: 100px;">List of all the active projects</h1>
<br/>

<table class="flat-table flat-table-3 center">
    <thead>
  <tr>
    <th>Project name</th>
    <th>Country</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @jobs.each do |job| %>
  <tr>
    <td><%= job.project_name %></td>
    <td><%= job.country %></td>
    <td><%= job.start_date %></td>
    <td><%= job.end_date %></td>
    <td><%= job.language %></td>
    <td><%= link_to 'Show', job, :class => "btn btn-sm btn-info" %></td>
    <td><%= link_to 'Edit', edit_job_path(job), :class => "btn btn-sm btn-warning" %></td>
    <td><% if job.status !=1 %><%= link_to 'Destroy', {controller: :jobs, action: :del, id: job.id},:class => "btn btn-sm btn-danger" %><% else %> <%= link_to 'Restore', {controller: :jobs, action: :restore, id: job.id},:class => "btn btn-sm btn-danger" %> <% end %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />
<div align="center" class="center center1">
<%= link_to 'New Project', new_job_path, :class => "btn btn-lg btn-primary center1" %>
</div>

app/views/jobs/index_user.html.erb
<h1 style="font-weight: 200; margin-left: 100px;">List of all the active Projects</h1>
<br/>

<table class="flat-table flat-table-3 center">
    <thead>
  <tr>
    <th>Project name</th>
    <th>Country</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Language</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
<% @jobs.each do |job| %>
  <% if job.status != 1 %>
  <tr>
    <td><%= job.project_name %></td>
    <td><%= job.country %></td>
    <td><%= job.start_date %></td>
    <td><%= job.end_date %></td>
    <td><%= job.language %></td>
    <td><%= link_to 'Show', job, :class => "btn btn-info" %></td>
    <td><%= link_to 'Apply',  {controller: "sessions", action: "apply", id: job }, :class => "btn btn-success" %></td>
  </tr>
  <% end %>
<% end %>
</tbody>
</table>

<br />

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<% if @job.status != 1 || current_user.is_admin %>

<div>

  <h1>Project Name: <%= @job.project_name %></h1>

</div>

<div >
    <h3>Job Country: <%= @job.country %></h3>
</div>

<div >
    <h3> Dates <%= @job.start_date %> -  <%= @job.end_date %> </h3>
</div>

<div >
  <h3><strong>Brief Description</strong>:<br/> <%= @job.brief_description %></h3>
</div>


<div >
  <h3><strong>Work Description</strong>: <%= @job.work_information %></h3>
</div>

<div >
  <h3><b>Language:</b>
  <%= @job.language %></h3>
</div>
<div >
  <h3><b>Other details:</b>
  <%= @job.other_details %></h3>
</div>
<% else %>
<p> The job you are looking for does not exist or has been removed from by the admin </p>
<% end %>
<% if @current_user.is_admin %>
<p> Status = <% if @job.status == 1 %> Deleted Job <% else %> Active Job <% end %> </p>
<%= link_to 'Back', :controller => "jobs", :action => "index" %>
<% if @job.status == 1 %>
<%= link_to 'Restore Delted Job', :controller => "jobs", :action => "restore" ,id: @job.id%>
<% end %>
<% else %>
<%= link_to 'Back', :controller => "jobs", :action => "index_user" %>
<% end %>